const UserAction = {
    REQUEST_REGISTER:"REQUEST_REGISTER",
    SUCCESS_REGISTER:"SUCCESS_REGISTER",
    REQUEST_LOGIN : "REQUEST_LOGIN",
    SUCCESS_LOGIN: "SUCCESS_LOGIN"
}
export default UserAction;
